name: Build and Test on Pull Request to Main

on:
    pull_request:
        branches:
            - main

env:
    DOTNET_VERSION: '6.0.x'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Install dependencies
              run: dotnet restore ./ClassTest.sln

            - name: Build
              run: dotnet build ./ClassTest.sln --no-restore

            - name: Test
              run: dotnet test ./ClassTest.sln --no-build
